// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGo3FXYVfrBoi9oj_DPSZlLZKDxABZ1c',
    appId: '1:756994781732:web:7f24fd1c76c88381b89eb1',
    messagingSenderId: '756994781732',
    projectId: 'first-proyect-e0c67',
    authDomain: 'first-proyect-e0c67.firebaseapp.com',
    storageBucket: 'first-proyect-e0c67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGL9A7r3x78ubVJOhgQasZptiCvFJZrjw',
    appId: '1:756994781732:android:76c05689adaeed20b89eb1',
    messagingSenderId: '756994781732',
    projectId: 'first-proyect-e0c67',
    storageBucket: 'first-proyect-e0c67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUucx1aa7rZj2oBpRo8y1Z0f9SqxoATdI',
    appId: '1:756994781732:ios:f954040ecc94dec6b89eb1',
    messagingSenderId: '756994781732',
    projectId: 'first-proyect-e0c67',
    storageBucket: 'first-proyect-e0c67.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUucx1aa7rZj2oBpRo8y1Z0f9SqxoATdI',
    appId: '1:756994781732:ios:f954040ecc94dec6b89eb1',
    messagingSenderId: '756994781732',
    projectId: 'first-proyect-e0c67',
    storageBucket: 'first-proyect-e0c67.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYGo3FXYVfrBoi9oj_DPSZlLZKDxABZ1c',
    appId: '1:756994781732:web:af2f4ea29d03da57b89eb1',
    messagingSenderId: '756994781732',
    projectId: 'first-proyect-e0c67',
    authDomain: 'first-proyect-e0c67.firebaseapp.com',
    storageBucket: 'first-proyect-e0c67.appspot.com',
  );
}
